#ifndef _ALTERA_KBANDIPSUBAFFINE_0_DDR_H_
#define _ALTERA_KBANDIPSUBAFFINE_0_DDR_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../../soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'KBandIPsubAffine_0_DDR' and devices
 * connected to the following master:
 *   m0
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'fft_ddr_bridge', class 'altera_address_span_extender'
 * The macros are prefixed with 'FFT_DDR_BRIDGE_'.
 * The prefix is the slave descriptor.
 */
#define FFT_DDR_BRIDGE_COMPONENT_TYPE altera_address_span_extender
#define FFT_DDR_BRIDGE_COMPONENT_NAME fft_ddr_bridge
#define FFT_DDR_BRIDGE_BASE 0x0
#define FFT_DDR_BRIDGE_SPAN 1073741824
#define FFT_DDR_BRIDGE_END 0x3fffffff
#define FFT_DDR_BRIDGE_BURSTCOUNT_WIDTH 5
#define FFT_DDR_BRIDGE_BYTEENABLE_WIDTH 16
#define FFT_DDR_BRIDGE_CNTL_ADDRESS_WIDTH 1
#define FFT_DDR_BRIDGE_DATA_WIDTH 128
#define FFT_DDR_BRIDGE_MASTER_ADDRESS_WIDTH 32
#define FFT_DDR_BRIDGE_MAX_BURST_BYTES 256
#define FFT_DDR_BRIDGE_MAX_BURST_WORDS 16
#define FFT_DDR_BRIDGE_SLAVE_ADDRESS_SHIFT 4
#define FFT_DDR_BRIDGE_SLAVE_ADDRESS_WIDTH 26
#define FFT_DDR_BRIDGE_SUB_WINDOW_COUNT 1


#endif /* _ALTERA_KBANDIPSUBAFFINE_0_DDR_H_ */
