-- FifoKBandIN.vhd

-- Generated using ACDS version 18.0 219

library IEEE;
library fifo_180;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FifoKBandIN is
	port (
		data    : in  std_logic_vector(2 downto 0) := (others => '0'); --  fifo_input.datain
		wrreq   : in  std_logic                    := '0';             --            .wrreq
		rdreq   : in  std_logic                    := '0';             --            .rdreq
		wrclk   : in  std_logic                    := '0';             --            .wrclk
		rdclk   : in  std_logic                    := '0';             --            .rdclk
		aclr    : in  std_logic                    := '0';             --            .aclr
		q       : out std_logic_vector(2 downto 0);                    -- fifo_output.dataout
		rdempty : out std_logic;                                       --            .rdempty
		wrfull  : out std_logic                                        --            .wrfull
	);
end entity FifoKBandIN;

architecture rtl of FifoKBandIN is
	component FifoKBandIN_fifo_180_oyffvha_cmp is
		port (
			data    : in  std_logic_vector(2 downto 0) := (others => 'X'); -- datain
			wrreq   : in  std_logic                    := 'X';             -- wrreq
			rdreq   : in  std_logic                    := 'X';             -- rdreq
			wrclk   : in  std_logic                    := 'X';             -- wrclk
			rdclk   : in  std_logic                    := 'X';             -- rdclk
			aclr    : in  std_logic                    := 'X';             -- aclr
			q       : out std_logic_vector(2 downto 0);                    -- dataout
			rdempty : out std_logic;                                       -- rdempty
			wrfull  : out std_logic                                        -- wrfull
		);
	end component FifoKBandIN_fifo_180_oyffvha_cmp;

	for fifo_0 : FifoKBandIN_fifo_180_oyffvha_cmp
		use entity fifo_180.FifoKBandIN_fifo_180_oyffvha;
begin

	fifo_0 : component FifoKBandIN_fifo_180_oyffvha_cmp
		port map (
			data    => data,    --  fifo_input.datain
			wrreq   => wrreq,   --            .wrreq
			rdreq   => rdreq,   --            .rdreq
			wrclk   => wrclk,   --            .wrclk
			rdclk   => rdclk,   --            .rdclk
			aclr    => aclr,    --            .aclr
			q       => q,       -- fifo_output.dataout
			rdempty => rdempty, --            .rdempty
			wrfull  => wrfull   --            .wrfull
		);

end architecture rtl; -- of FifoKBandIN
