// soc_system_mm_interconnect_6.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 196

`timescale 1 ps / 1 ps
module soc_system_mm_interconnect_6 (
		input  wire         pll_0_outclk0_clk,                                    //                                  pll_0_outclk0.clk
		input  wire         fft_ddr_bridge_reset_reset_bridge_in_reset_reset,     //     fft_ddr_bridge_reset_reset_bridge_in_reset.reset
		input  wire         KBandIPsubAffine_0_reset_reset_bridge_in_reset_reset, // KBandIPsubAffine_0_reset_reset_bridge_in_reset.reset
		input  wire [29:0]  KBandIPsubAffine_0_m0_address,                        //                          KBandIPsubAffine_0_m0.address
		output wire         KBandIPsubAffine_0_m0_waitrequest,                    //                                               .waitrequest
		input  wire [4:0]   KBandIPsubAffine_0_m0_burstcount,                     //                                               .burstcount
		input  wire [15:0]  KBandIPsubAffine_0_m0_byteenable,                     //                                               .byteenable
		input  wire         KBandIPsubAffine_0_m0_read,                           //                                               .read
		output wire [127:0] KBandIPsubAffine_0_m0_readdata,                       //                                               .readdata
		output wire         KBandIPsubAffine_0_m0_readdatavalid,                  //                                               .readdatavalid
		input  wire         KBandIPsubAffine_0_m0_write,                          //                                               .write
		input  wire [127:0] KBandIPsubAffine_0_m0_writedata,                      //                                               .writedata
		input  wire         KBandIPsubAffine_0_m0_debugaccess,                    //                                               .debugaccess
		output wire [25:0]  fft_ddr_bridge_windowed_slave_address,                //                  fft_ddr_bridge_windowed_slave.address
		output wire         fft_ddr_bridge_windowed_slave_write,                  //                                               .write
		output wire         fft_ddr_bridge_windowed_slave_read,                   //                                               .read
		input  wire [127:0] fft_ddr_bridge_windowed_slave_readdata,               //                                               .readdata
		output wire [127:0] fft_ddr_bridge_windowed_slave_writedata,              //                                               .writedata
		output wire [4:0]   fft_ddr_bridge_windowed_slave_burstcount,             //                                               .burstcount
		output wire [15:0]  fft_ddr_bridge_windowed_slave_byteenable,             //                                               .byteenable
		input  wire         fft_ddr_bridge_windowed_slave_readdatavalid,          //                                               .readdatavalid
		input  wire         fft_ddr_bridge_windowed_slave_waitrequest             //                                               .waitrequest
	);

	wire          kbandipsubaffine_0_m0_translator_avalon_universal_master_0_waitrequest;   // fft_ddr_bridge_windowed_slave_translator:uav_waitrequest -> KBandIPsubAffine_0_m0_translator:uav_waitrequest
	wire  [127:0] kbandipsubaffine_0_m0_translator_avalon_universal_master_0_readdata;      // fft_ddr_bridge_windowed_slave_translator:uav_readdata -> KBandIPsubAffine_0_m0_translator:uav_readdata
	wire          kbandipsubaffine_0_m0_translator_avalon_universal_master_0_debugaccess;   // KBandIPsubAffine_0_m0_translator:uav_debugaccess -> fft_ddr_bridge_windowed_slave_translator:uav_debugaccess
	wire   [29:0] kbandipsubaffine_0_m0_translator_avalon_universal_master_0_address;       // KBandIPsubAffine_0_m0_translator:uav_address -> fft_ddr_bridge_windowed_slave_translator:uav_address
	wire          kbandipsubaffine_0_m0_translator_avalon_universal_master_0_read;          // KBandIPsubAffine_0_m0_translator:uav_read -> fft_ddr_bridge_windowed_slave_translator:uav_read
	wire   [15:0] kbandipsubaffine_0_m0_translator_avalon_universal_master_0_byteenable;    // KBandIPsubAffine_0_m0_translator:uav_byteenable -> fft_ddr_bridge_windowed_slave_translator:uav_byteenable
	wire          kbandipsubaffine_0_m0_translator_avalon_universal_master_0_readdatavalid; // fft_ddr_bridge_windowed_slave_translator:uav_readdatavalid -> KBandIPsubAffine_0_m0_translator:uav_readdatavalid
	wire          kbandipsubaffine_0_m0_translator_avalon_universal_master_0_lock;          // KBandIPsubAffine_0_m0_translator:uav_lock -> fft_ddr_bridge_windowed_slave_translator:uav_lock
	wire          kbandipsubaffine_0_m0_translator_avalon_universal_master_0_write;         // KBandIPsubAffine_0_m0_translator:uav_write -> fft_ddr_bridge_windowed_slave_translator:uav_write
	wire  [127:0] kbandipsubaffine_0_m0_translator_avalon_universal_master_0_writedata;     // KBandIPsubAffine_0_m0_translator:uav_writedata -> fft_ddr_bridge_windowed_slave_translator:uav_writedata
	wire    [8:0] kbandipsubaffine_0_m0_translator_avalon_universal_master_0_burstcount;    // KBandIPsubAffine_0_m0_translator:uav_burstcount -> fft_ddr_bridge_windowed_slave_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (30),
		.AV_DATA_W                   (128),
		.AV_BURSTCOUNT_W             (5),
		.AV_BYTEENABLE_W             (16),
		.UAV_ADDRESS_W               (30),
		.UAV_BURSTCOUNT_W            (9),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (16),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (1),
		.UAV_CONSTANT_BURST_BEHAVIOR (1),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) kbandipsubaffine_0_m0_translator (
		.clk                    (pll_0_outclk0_clk),                                                        //                       clk.clk
		.reset                  (fft_ddr_bridge_reset_reset_bridge_in_reset_reset),                         //                     reset.reset
		.uav_address            (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (KBandIPsubAffine_0_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (KBandIPsubAffine_0_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (KBandIPsubAffine_0_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (KBandIPsubAffine_0_m0_byteenable),                                         //                          .byteenable
		.av_read                (KBandIPsubAffine_0_m0_read),                                               //                          .read
		.av_readdata            (KBandIPsubAffine_0_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (KBandIPsubAffine_0_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (KBandIPsubAffine_0_m0_write),                                              //                          .write
		.av_writedata           (KBandIPsubAffine_0_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (KBandIPsubAffine_0_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                                     //               (terminated)
		.av_begintransfer       (1'b0),                                                                     //               (terminated)
		.av_chipselect          (1'b0),                                                                     //               (terminated)
		.av_lock                (1'b0),                                                                     //               (terminated)
		.uav_clken              (),                                                                         //               (terminated)
		.av_clken               (1'b1),                                                                     //               (terminated)
		.uav_response           (2'b00),                                                                    //               (terminated)
		.av_response            (),                                                                         //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                     //               (terminated)
		.av_writeresponsevalid  ()                                                                          //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (26),
		.AV_DATA_W                      (128),
		.UAV_DATA_W                     (128),
		.AV_BURSTCOUNT_W                (5),
		.AV_BYTEENABLE_W                (16),
		.UAV_BYTEENABLE_W               (16),
		.UAV_ADDRESS_W                  (30),
		.UAV_BURSTCOUNT_W               (9),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (16),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) fft_ddr_bridge_windowed_slave_translator (
		.clk                    (pll_0_outclk0_clk),                                                        //                      clk.clk
		.reset                  (fft_ddr_bridge_reset_reset_bridge_in_reset_reset),                         //                    reset.reset
		.uav_address            (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (kbandipsubaffine_0_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (fft_ddr_bridge_windowed_slave_address),                                    //      avalon_anti_slave_0.address
		.av_write               (fft_ddr_bridge_windowed_slave_write),                                      //                         .write
		.av_read                (fft_ddr_bridge_windowed_slave_read),                                       //                         .read
		.av_readdata            (fft_ddr_bridge_windowed_slave_readdata),                                   //                         .readdata
		.av_writedata           (fft_ddr_bridge_windowed_slave_writedata),                                  //                         .writedata
		.av_burstcount          (fft_ddr_bridge_windowed_slave_burstcount),                                 //                         .burstcount
		.av_byteenable          (fft_ddr_bridge_windowed_slave_byteenable),                                 //                         .byteenable
		.av_readdatavalid       (fft_ddr_bridge_windowed_slave_readdatavalid),                              //                         .readdatavalid
		.av_waitrequest         (fft_ddr_bridge_windowed_slave_waitrequest),                                //                         .waitrequest
		.av_begintransfer       (),                                                                         //              (terminated)
		.av_beginbursttransfer  (),                                                                         //              (terminated)
		.av_writebyteenable     (),                                                                         //              (terminated)
		.av_lock                (),                                                                         //              (terminated)
		.av_chipselect          (),                                                                         //              (terminated)
		.av_clken               (),                                                                         //              (terminated)
		.uav_clken              (1'b0),                                                                     //              (terminated)
		.av_debugaccess         (),                                                                         //              (terminated)
		.av_outputenable        (),                                                                         //              (terminated)
		.uav_response           (),                                                                         //              (terminated)
		.av_response            (2'b00),                                                                    //              (terminated)
		.uav_writeresponsevalid (),                                                                         //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                      //              (terminated)
	);

endmodule
