#ifndef _ALTERA_KBANDIPSUB_KBANDINPUT_1_H_
#define _ALTERA_KBANDIPSUB_KBANDINPUT_1_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../../soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'KBandIPsub_KBandInput_1' and devices
 * connected to the following master:
 *   mm_read
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'KBandIPsub_KBandInput_1', class 'altera_msgdma'.
 * The macros have no prefix.
 */
#define BURST_ENABLE 0
#define BURST_WRAPPING_SUPPORT 0
#define CHANNEL_ENABLE 0
#define CHANNEL_ENABLE_DERIVED 0
#define CHANNEL_WIDTH 8
#define DATA_FIFO_DEPTH 32
#define DATA_WIDTH 32
#define DESCRIPTOR_FIFO_DEPTH 128
#define DMA_MODE 1
#define ENHANCED_FEATURES 0
#define ERROR_ENABLE 0
#define ERROR_ENABLE_DERIVED 0
#define ERROR_WIDTH 8
#define MAX_BURST_COUNT 2
#define MAX_BYTE 4096
#define MAX_STRIDE 1
#define PACKET_ENABLE 0
#define PACKET_ENABLE_DERIVED 0
#define PREFETCHER_ENABLE 0
#define PROGRAMMABLE_BURST_ENABLE 0
#define RESPONSE_PORT 2
#define STRIDE_ENABLE 0
#define STRIDE_ENABLE_DERIVED 0
#define TRANSFER_TYPE Full Word Accesses Only

/*
 * Macros for device 'KBandIPsub_onchip_mem_LW', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'KBANDIPSUB_ONCHIP_MEM_LW_'.
 * The prefix is the slave descriptor.
 */
#define KBANDIPSUB_ONCHIP_MEM_LW_COMPONENT_TYPE altera_avalon_onchip_memory2
#define KBANDIPSUB_ONCHIP_MEM_LW_COMPONENT_NAME KBandIPsub_onchip_mem_LW
#define KBANDIPSUB_ONCHIP_MEM_LW_BASE 0x0
#define KBANDIPSUB_ONCHIP_MEM_LW_SPAN 4096
#define KBANDIPSUB_ONCHIP_MEM_LW_END 0xfff
#define KBANDIPSUB_ONCHIP_MEM_LW_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define KBANDIPSUB_ONCHIP_MEM_LW_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define KBANDIPSUB_ONCHIP_MEM_LW_CONTENTS_INFO ""
#define KBANDIPSUB_ONCHIP_MEM_LW_DUAL_PORT 0
#define KBANDIPSUB_ONCHIP_MEM_LW_GUI_RAM_BLOCK_TYPE AUTO
#define KBANDIPSUB_ONCHIP_MEM_LW_INIT_CONTENTS_FILE soc_system_KBandIPsub_onchip_mem_LW
#define KBANDIPSUB_ONCHIP_MEM_LW_INIT_MEM_CONTENT 1
#define KBANDIPSUB_ONCHIP_MEM_LW_INSTANCE_ID NONE
#define KBANDIPSUB_ONCHIP_MEM_LW_NON_DEFAULT_INIT_FILE_ENABLED 0
#define KBANDIPSUB_ONCHIP_MEM_LW_RAM_BLOCK_TYPE AUTO
#define KBANDIPSUB_ONCHIP_MEM_LW_READ_DURING_WRITE_MODE DONT_CARE
#define KBANDIPSUB_ONCHIP_MEM_LW_SINGLE_CLOCK_OP 0
#define KBANDIPSUB_ONCHIP_MEM_LW_SIZE_MULTIPLE 1
#define KBANDIPSUB_ONCHIP_MEM_LW_SIZE_VALUE 4096
#define KBANDIPSUB_ONCHIP_MEM_LW_WRITABLE 1
#define KBANDIPSUB_ONCHIP_MEM_LW_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define KBANDIPSUB_ONCHIP_MEM_LW_MEMORY_INFO_GENERATE_DAT_SYM 1
#define KBANDIPSUB_ONCHIP_MEM_LW_MEMORY_INFO_GENERATE_HEX 1
#define KBANDIPSUB_ONCHIP_MEM_LW_MEMORY_INFO_HAS_BYTE_LANE 0
#define KBANDIPSUB_ONCHIP_MEM_LW_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define KBANDIPSUB_ONCHIP_MEM_LW_MEMORY_INFO_MEM_INIT_DATA_WIDTH 128
#define KBANDIPSUB_ONCHIP_MEM_LW_MEMORY_INFO_MEM_INIT_FILENAME soc_system_KBandIPsub_onchip_mem_LW

/*
 * Macros for device 'fft_ddr_bridge', class 'altera_address_span_extender'
 * The macros are prefixed with 'FFT_DDR_BRIDGE_'.
 * The prefix is the slave descriptor.
 */
#define FFT_DDR_BRIDGE_COMPONENT_TYPE altera_address_span_extender
#define FFT_DDR_BRIDGE_COMPONENT_NAME fft_ddr_bridge
#define FFT_DDR_BRIDGE_BASE 0x40000000
#define FFT_DDR_BRIDGE_SPAN 1073741824
#define FFT_DDR_BRIDGE_END 0x7fffffff
#define FFT_DDR_BRIDGE_BURSTCOUNT_WIDTH 5
#define FFT_DDR_BRIDGE_BYTEENABLE_WIDTH 16
#define FFT_DDR_BRIDGE_CNTL_ADDRESS_WIDTH 1
#define FFT_DDR_BRIDGE_DATA_WIDTH 128
#define FFT_DDR_BRIDGE_MASTER_ADDRESS_WIDTH 32
#define FFT_DDR_BRIDGE_MAX_BURST_BYTES 256
#define FFT_DDR_BRIDGE_MAX_BURST_WORDS 16
#define FFT_DDR_BRIDGE_SLAVE_ADDRESS_SHIFT 4
#define FFT_DDR_BRIDGE_SLAVE_ADDRESS_WIDTH 26
#define FFT_DDR_BRIDGE_SUB_WINDOW_COUNT 1


#endif /* _ALTERA_KBANDIPSUB_KBANDINPUT_1_H_ */
