-- KBandIPsubPro_clk_0.vhd

-- Generated using ACDS version 19.1 240

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity KBandIPsubPro_clk_0 is
	port (
		in_clk      : in  std_logic := '0'; --       clk_in.clk
		reset_n     : in  std_logic := '0'; -- clk_in_reset.reset_n
		clk_out     : out std_logic;        --          clk.clk
		reset_n_out : out std_logic         --    clk_reset.reset_n
	);
end entity KBandIPsubPro_clk_0;

architecture rtl of KBandIPsubPro_clk_0 is
begin

	clk_out <= in_clk;

	reset_n_out <= reset_n;

end architecture rtl; -- of KBandIPsubPro_clk_0
