#ifndef _ALTERA_KBANDIP_KBANDINPUT_1_H_
#define _ALTERA_KBANDIP_KBANDINPUT_1_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../../soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'KBandIP_KBandInput_1' and devices
 * connected to the following master:
 *   mm_read
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'KBandIP_KBandInput_1', class 'altera_msgdma'.
 * The macros have no prefix.
 */
#define BURST_ENABLE 0
#define BURST_WRAPPING_SUPPORT 0
#define CHANNEL_ENABLE 0
#define CHANNEL_ENABLE_DERIVED 0
#define CHANNEL_WIDTH 8
#define DATA_FIFO_DEPTH 32
#define DATA_WIDTH 8
#define DESCRIPTOR_FIFO_DEPTH 128
#define DMA_MODE 1
#define ENHANCED_FEATURES 0
#define ERROR_ENABLE 0
#define ERROR_ENABLE_DERIVED 0
#define ERROR_WIDTH 8
#define MAX_BURST_COUNT 2
#define MAX_BYTE 1024
#define MAX_STRIDE 1
#define PACKET_ENABLE 0
#define PACKET_ENABLE_DERIVED 0
#define PREFETCHER_ENABLE 0
#define PROGRAMMABLE_BURST_ENABLE 0
#define RESPONSE_PORT 2
#define STRIDE_ENABLE 0
#define STRIDE_ENABLE_DERIVED 0
#define TRANSFER_TYPE Aligned Accesses

/*
 * Macros for device 'fft_ddr_bridge', class 'altera_address_span_extender'
 * The macros are prefixed with 'FFT_DDR_BRIDGE_'.
 * The prefix is the slave descriptor.
 */
#define FFT_DDR_BRIDGE_COMPONENT_TYPE altera_address_span_extender
#define FFT_DDR_BRIDGE_COMPONENT_NAME fft_ddr_bridge
#define FFT_DDR_BRIDGE_BASE 0x0
#define FFT_DDR_BRIDGE_SPAN 1073741824
#define FFT_DDR_BRIDGE_END 0x3fffffff
#define FFT_DDR_BRIDGE_BURSTCOUNT_WIDTH 5
#define FFT_DDR_BRIDGE_BYTEENABLE_WIDTH 16
#define FFT_DDR_BRIDGE_CNTL_ADDRESS_WIDTH 1
#define FFT_DDR_BRIDGE_DATA_WIDTH 128
#define FFT_DDR_BRIDGE_MASTER_ADDRESS_WIDTH 32
#define FFT_DDR_BRIDGE_MAX_BURST_BYTES 256
#define FFT_DDR_BRIDGE_MAX_BURST_WORDS 16
#define FFT_DDR_BRIDGE_SLAVE_ADDRESS_SHIFT 4
#define FFT_DDR_BRIDGE_SLAVE_ADDRESS_WIDTH 26
#define FFT_DDR_BRIDGE_SUB_WINDOW_COUNT 1


#endif /* _ALTERA_KBANDIP_KBANDINPUT_1_H_ */
