/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2' in SOPC Builder design 'unsaved'
 * SOPC Builder design path: ../../unsaved.sopcinfo
 *
 * Generated: Wed Aug 24 15:10:33 COT 2016
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * Altera_UP_SD_Card_Avalon_Interface_0 configuration as viewed by dma_sd_card_rd_read_master
 *
 */

#define DMA_SD_CARD_RD_READ_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_BASE 0x0
#define DMA_SD_CARD_RD_READ_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_IRQ -1
#define DMA_SD_CARD_RD_READ_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_SD_CARD_RD_READ_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_NAME "/dev/Altera_UP_SD_Card_Avalon_Interface_0"
#define DMA_SD_CARD_RD_READ_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_SPAN 1024
#define DMA_SD_CARD_RD_READ_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_TYPE "Altera_UP_SD_Card_Avalon_Interface"


/*
 * Altera_UP_SD_Card_Avalon_Interface_0 configuration as viewed by dma_sd_card_wr_write_master
 *
 */

#define DMA_SD_CARD_WR_WRITE_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_BASE 0x0
#define DMA_SD_CARD_WR_WRITE_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_IRQ -1
#define DMA_SD_CARD_WR_WRITE_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_SD_CARD_WR_WRITE_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_NAME "/dev/Altera_UP_SD_Card_Avalon_Interface_0"
#define DMA_SD_CARD_WR_WRITE_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_SPAN 1024
#define DMA_SD_CARD_WR_WRITE_MASTER_ALTERA_UP_SD_CARD_AVALON_INTERFACE_0_TYPE "Altera_UP_SD_Card_Avalon_Interface"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x08000820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1c
#define ALT_CPU_DCACHE_BYPASS_MASK 0x80000000
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 2048
#define ALT_CPU_EXCEPTION_ADDR 0x00000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0x1c
#define ALT_CPU_NAME "nios2_gen2"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x08000820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x1c
#define NIOS2_DCACHE_BYPASS_MASK 0x80000000
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 2048
#define NIOS2_EXCEPTION_ADDR 0x00000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0x1c
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_DMA
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_NIOS2_GEN2


/*
 * KBandInput configuration
 *
 */

#define ALT_MODULE_CLASS_KBandInput altera_avalon_sgdma
#define KBANDINPUT_ADDRESS_WIDTH 32
#define KBANDINPUT_ALWAYS_DO_MAX_BURST 1
#define KBANDINPUT_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define KBANDINPUT_AVALON_MM_BYTE_REORDER_MODE 0
#define KBANDINPUT_BASE 0x8001000
#define KBANDINPUT_BURST_DATA_WIDTH 8
#define KBANDINPUT_BURST_TRANSFER 0
#define KBANDINPUT_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define KBANDINPUT_CHAIN_WRITEBACK_DATA_WIDTH 32
#define KBANDINPUT_COMMAND_FIFO_DATA_WIDTH 104
#define KBANDINPUT_CONTROL_DATA_WIDTH 8
#define KBANDINPUT_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define KBANDINPUT_CONTROL_SLAVE_DATA_WIDTH 32
#define KBANDINPUT_DESCRIPTOR_READ_BURST 0
#define KBANDINPUT_DESC_DATA_WIDTH 32
#define KBANDINPUT_HAS_READ_BLOCK 1
#define KBANDINPUT_HAS_WRITE_BLOCK 0
#define KBANDINPUT_IN_ERROR_WIDTH 0
#define KBANDINPUT_IRQ 0
#define KBANDINPUT_IRQ_INTERRUPT_CONTROLLER_ID 0
#define KBANDINPUT_NAME "/dev/KBandInput"
#define KBANDINPUT_OUT_ERROR_WIDTH 0
#define KBANDINPUT_READ_BLOCK_DATA_WIDTH 32
#define KBANDINPUT_READ_BURSTCOUNT_WIDTH 4
#define KBANDINPUT_SPAN 64
#define KBANDINPUT_STATUS_TOKEN_DATA_WIDTH 24
#define KBANDINPUT_STREAM_DATA_WIDTH 32
#define KBANDINPUT_SYMBOLS_PER_BEAT 4
#define KBANDINPUT_TYPE "altera_avalon_sgdma"
#define KBANDINPUT_UNALIGNED_TRANSFER 0
#define KBANDINPUT_WRITE_BLOCK_DATA_WIDTH 32
#define KBANDINPUT_WRITE_BURSTCOUNT_WIDTH 4


/*
 * KBandOutput configuration
 *
 */

#define ALT_MODULE_CLASS_KBandOutput altera_avalon_sgdma
#define KBANDOUTPUT_ADDRESS_WIDTH 32
#define KBANDOUTPUT_ALWAYS_DO_MAX_BURST 1
#define KBANDOUTPUT_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define KBANDOUTPUT_AVALON_MM_BYTE_REORDER_MODE 0
#define KBANDOUTPUT_BASE 0x8001040
#define KBANDOUTPUT_BURST_DATA_WIDTH 8
#define KBANDOUTPUT_BURST_TRANSFER 0
#define KBANDOUTPUT_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define KBANDOUTPUT_CHAIN_WRITEBACK_DATA_WIDTH 32
#define KBANDOUTPUT_COMMAND_FIFO_DATA_WIDTH 104
#define KBANDOUTPUT_CONTROL_DATA_WIDTH 8
#define KBANDOUTPUT_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define KBANDOUTPUT_CONTROL_SLAVE_DATA_WIDTH 32
#define KBANDOUTPUT_DESCRIPTOR_READ_BURST 0
#define KBANDOUTPUT_DESC_DATA_WIDTH 32
#define KBANDOUTPUT_HAS_READ_BLOCK 0
#define KBANDOUTPUT_HAS_WRITE_BLOCK 1
#define KBANDOUTPUT_IN_ERROR_WIDTH 0
#define KBANDOUTPUT_IRQ 1
#define KBANDOUTPUT_IRQ_INTERRUPT_CONTROLLER_ID 0
#define KBANDOUTPUT_NAME "/dev/KBandOutput"
#define KBANDOUTPUT_OUT_ERROR_WIDTH 0
#define KBANDOUTPUT_READ_BLOCK_DATA_WIDTH 32
#define KBANDOUTPUT_READ_BURSTCOUNT_WIDTH 4
#define KBANDOUTPUT_SPAN 64
#define KBANDOUTPUT_STATUS_TOKEN_DATA_WIDTH 24
#define KBANDOUTPUT_STREAM_DATA_WIDTH 32
#define KBANDOUTPUT_SYMBOLS_PER_BEAT 4
#define KBANDOUTPUT_TYPE "altera_avalon_sgdma"
#define KBANDOUTPUT_UNALIGNED_TRANSFER 0
#define KBANDOUTPUT_WRITE_BLOCK_DATA_WIDTH 32
#define KBANDOUTPUT_WRITE_BURSTCOUNT_WIDTH 4


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone V"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/null"
#define ALT_STDERR_BASE 0x0
#define ALT_STDERR_DEV null
#define ALT_STDERR_TYPE ""
#define ALT_STDIN "/dev/null"
#define ALT_STDIN_BASE 0x0
#define ALT_STDIN_DEV null
#define ALT_STDIN_TYPE ""
#define ALT_STDOUT "/dev/null"
#define ALT_STDOUT_BASE 0x0
#define ALT_STDOUT_DEV null
#define ALT_STDOUT_TYPE ""
#define ALT_SYSTEM_NAME "unsaved"


/*
 * dma_sd_card_rd configuration
 *
 */

#define ALT_MODULE_CLASS_dma_sd_card_rd altera_avalon_dma
#define DMA_SD_CARD_RD_ALLOW_BYTE_TRANSACTIONS 0
#define DMA_SD_CARD_RD_ALLOW_DOUBLEWORD_TRANSACTIONS 0
#define DMA_SD_CARD_RD_ALLOW_HW_TRANSACTIONS 0
#define DMA_SD_CARD_RD_ALLOW_QUADWORD_TRANSACTIONS 0
#define DMA_SD_CARD_RD_ALLOW_WORD_TRANSACTIONS 1
#define DMA_SD_CARD_RD_BASE 0x80010a0
#define DMA_SD_CARD_RD_IRQ 3
#define DMA_SD_CARD_RD_IRQ_INTERRUPT_CONTROLLER_ID 0
#define DMA_SD_CARD_RD_LENGTHWIDTH 13
#define DMA_SD_CARD_RD_MAX_BURST_SIZE 128
#define DMA_SD_CARD_RD_NAME "/dev/dma_sd_card_rd"
#define DMA_SD_CARD_RD_SPAN 32
#define DMA_SD_CARD_RD_TYPE "altera_avalon_dma"


/*
 * dma_sd_card_wr configuration
 *
 */

#define ALT_MODULE_CLASS_dma_sd_card_wr altera_avalon_dma
#define DMA_SD_CARD_WR_ALLOW_BYTE_TRANSACTIONS 0
#define DMA_SD_CARD_WR_ALLOW_DOUBLEWORD_TRANSACTIONS 0
#define DMA_SD_CARD_WR_ALLOW_HW_TRANSACTIONS 0
#define DMA_SD_CARD_WR_ALLOW_QUADWORD_TRANSACTIONS 0
#define DMA_SD_CARD_WR_ALLOW_WORD_TRANSACTIONS 1
#define DMA_SD_CARD_WR_BASE 0x8001080
#define DMA_SD_CARD_WR_IRQ 2
#define DMA_SD_CARD_WR_IRQ_INTERRUPT_CONTROLLER_ID 0
#define DMA_SD_CARD_WR_LENGTHWIDTH 13
#define DMA_SD_CARD_WR_MAX_BURST_SIZE 128
#define DMA_SD_CARD_WR_NAME "/dev/dma_sd_card_wr"
#define DMA_SD_CARD_WR_SPAN 32
#define DMA_SD_CARD_WR_TYPE "altera_avalon_dma"


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK none
#define ALT_TIMESTAMP_CLK none


/*
 * sdram_controller configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_controller altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_BASE 0x0
#define SDRAM_CONTROLLER_CAS_LATENCY 3
#define SDRAM_CONTROLLER_CONTENTS_INFO
#define SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 2
#define SDRAM_CONTROLLER_IRQ -1
#define SDRAM_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_CONTROLLER_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_NAME "/dev/sdram_controller"
#define SDRAM_CONTROLLER_POWERUP_DELAY 200.0
#define SDRAM_CONTROLLER_REFRESH_PERIOD 7.8125
#define SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 0x19
#define SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_SDRAM_COL_WIDTH 10
#define SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 32
#define SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_SHARED_DATA 0
#define SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_SPAN 134217728
#define SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_CONTROLLER_T_AC 5.5
#define SDRAM_CONTROLLER_T_MRD 3
#define SDRAM_CONTROLLER_T_RCD 20.0
#define SDRAM_CONTROLLER_T_RFC 70.0
#define SDRAM_CONTROLLER_T_RP 20.0
#define SDRAM_CONTROLLER_T_WR 14.0


/*
 * sdram_controller configuration as viewed by KBandInput_m_read
 *
 */

#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_BASE 0x0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_CAS_LATENCY 3
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_CONTENTS_INFO
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 2
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_IRQ -1
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_IS_INITIALIZED 1
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_NAME "/dev/sdram_controller"
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_POWERUP_DELAY 200.0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_REFRESH_PERIOD 7.8125
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 0x19
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SDRAM_COL_WIDTH 10
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 32
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SHARED_DATA 0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_SPAN 134217728
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_TYPE "altera_avalon_new_sdram_controller"
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_T_AC 5.5
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_T_MRD 3
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_T_RCD 20.0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_T_RFC 70.0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_T_RP 20.0
#define KBANDINPUT_M_READ_SDRAM_CONTROLLER_T_WR 14.0


/*
 * sdram_controller configuration as viewed by KBandOutput_m_write
 *
 */

#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_BASE 0x0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_CAS_LATENCY 3
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_CONTENTS_INFO
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 2
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_IRQ -1
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_IS_INITIALIZED 1
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_NAME "/dev/sdram_controller"
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_POWERUP_DELAY 200.0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_REFRESH_PERIOD 7.8125
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 0x19
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SDRAM_COL_WIDTH 10
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 32
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SHARED_DATA 0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_SPAN 134217728
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_TYPE "altera_avalon_new_sdram_controller"
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_T_AC 5.5
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_T_MRD 3
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_T_RCD 20.0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_T_RFC 70.0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_T_RP 20.0
#define KBANDOUTPUT_M_WRITE_SDRAM_CONTROLLER_T_WR 14.0


/*
 * sdram_controller configuration as viewed by dma_sd_card_rd_write_master
 *
 */

#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_BASE 0x0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_CAS_LATENCY 3
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_CONTENTS_INFO
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 2
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_IRQ -1
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_IS_INITIALIZED 1
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_NAME "/dev/sdram_controller"
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_POWERUP_DELAY 200.0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_REFRESH_PERIOD 7.8125
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 0x19
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SDRAM_COL_WIDTH 10
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 32
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SHARED_DATA 0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_SPAN 134217728
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_TYPE "altera_avalon_new_sdram_controller"
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_T_AC 5.5
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_T_MRD 3
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_T_RCD 20.0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_T_RFC 70.0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_T_RP 20.0
#define DMA_SD_CARD_RD_WRITE_MASTER_SDRAM_CONTROLLER_T_WR 14.0


/*
 * sdram_controller configuration as viewed by dma_sd_card_wr_read_master
 *
 */

#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_BASE 0x0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_CAS_LATENCY 3
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_CONTENTS_INFO
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_INIT_NOP_DELAY 0.0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_INIT_REFRESH_COMMANDS 2
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_IRQ -1
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_IRQ_INTERRUPT_CONTROLLER_ID -1
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_IS_INITIALIZED 1
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_NAME "/dev/sdram_controller"
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_POWERUP_DELAY 200.0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_REFRESH_PERIOD 7.8125
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_REGISTER_DATA_IN 1
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SDRAM_ADDR_WIDTH 0x19
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SDRAM_BANK_WIDTH 2
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SDRAM_COL_WIDTH 10
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SDRAM_DATA_WIDTH 32
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SDRAM_NUM_BANKS 4
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SDRAM_NUM_CHIPSELECTS 1
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SDRAM_ROW_WIDTH 13
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SHARED_DATA 0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SIM_MODEL_BASE 0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_SPAN 134217728
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_STARVATION_INDICATOR 0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_TRISTATE_BRIDGE_SLAVE ""
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_TYPE "altera_avalon_new_sdram_controller"
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_T_AC 5.5
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_T_MRD 3
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_T_RCD 20.0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_T_RFC 70.0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_T_RP 20.0
#define DMA_SD_CARD_WR_READ_MASTER_SDRAM_CONTROLLER_T_WR 14.0

#endif /* __SYSTEM_H_ */
