-- FifoKBandOUT.vhd

-- Generated using ACDS version 18.0 219

library IEEE;
library fifo_180;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FifoKBandOUT is
	GENERIC(
		bitsIN		: 	natural  :=	128;	--MULTIPLOS DE 32
		bitsOUT		: 	natural  :=	32;	--32
		widthu		: 	natural  :=	8
	);
	port (
		data    : in  std_logic_vector(bitsIN-1 DOWNTO 0) := (others => '0'); --  fifo_input.datain
		wrreq   : in  std_logic                       := '0';             --            .wrreq
		rdreq   : in  std_logic                       := '0';             --            .rdreq
		wrclk   : in  std_logic                       := '0';             --            .wrclk
		rdclk   : in  std_logic                       := '0';             --            .rdclk
		aclr    : in  std_logic                       := '0';             --            .aclr
		q       : out std_logic_vector(bitsOUT-1 DOWNTO 0);                     -- fifo_output.dataout
		wrusedw : out std_logic_vector(2 downto 0);                       --            .wrusedw
		rdempty : out std_logic;                                          --            .rdempty
		wrfull  : out std_logic                                           --            .wrfull
	);
end entity FifoKBandOUT;

architecture rtl of FifoKBandOUT is
	component FifoKBandOUT_fifo_180_mgzb3ui_cmp is
		GENERIC(
			bitsIN		: 	natural  :=	128;	--MULTIPLOS DE 32
			bitsOUT		: 	natural  :=	32;	--32
			widthu		: 	natural  :=	8
		);
		port (
			data    : in  std_logic_vector(bitsIN-1 DOWNTO 0) := (others => 'X'); -- datain
			wrreq   : in  std_logic                       := 'X';             -- wrreq
			rdreq   : in  std_logic                       := 'X';             -- rdreq
			wrclk   : in  std_logic                       := 'X';             -- wrclk
			rdclk   : in  std_logic                       := 'X';             -- rdclk
			aclr    : in  std_logic                       := 'X';             -- aclr
			q       : out std_logic_vector(bitsOUT-1 DOWNTO 0);                     -- dataout
			wrusedw : out std_logic_vector(2 downto 0);                       -- wrusedw
			rdempty : out std_logic;                                          -- rdempty
			wrfull  : out std_logic                                           -- wrfull
		);
	end component FifoKBandOUT_fifo_180_mgzb3ui_cmp;

	for fifo_0 : FifoKBandOUT_fifo_180_mgzb3ui_cmp
		use entity fifo_180.FifoKBandOUT_fifo_180_mgzb3ui;
begin

	fifo_0 : component FifoKBandOUT_fifo_180_mgzb3ui_cmp
		generic map(bitsIN, bitsOUT, widthu)
		port map (
			data    => data,    --  fifo_input.datain
			wrreq   => wrreq,   --            .wrreq
			rdreq   => rdreq,   --            .rdreq
			wrclk   => wrclk,   --            .wrclk
			rdclk   => rdclk,   --            .rdclk
			aclr    => aclr,    --            .aclr
			q       => q,       -- fifo_output.dataout
			wrusedw => wrusedw, --            .wrusedw
			rdempty => rdempty, --            .rdempty
			wrfull  => wrfull   --            .wrfull
		);

end architecture rtl; -- of FifoKBandOUT
