-- KBandIPsubPro_onchip_mem_LW.vhd

-- Generated using ACDS version 19.1 240

library IEEE;
library altera_avalon_onchip_memory2_191;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity KBandIPsubPro_onchip_mem_LW is
	port (
		clk        : in  std_logic                     := '0';             --   clk1.clk
		address    : in  std_logic_vector(12 downto 0) := (others => '0'); --     s1.address
		clken      : in  std_logic                     := '0';             --       .clken
		chipselect : in  std_logic                     := '0';             --       .chipselect
		write      : in  std_logic                     := '0';             --       .write
		readdata   : out std_logic_vector(31 downto 0);                    --       .readdata
		writedata  : in  std_logic_vector(31 downto 0) := (others => '0'); --       .writedata
		byteenable : in  std_logic_vector(3 downto 0)  := (others => '0'); --       .byteenable
		reset      : in  std_logic                     := '0';             -- reset1.reset
		reset_req  : in  std_logic                     := '0'              --       .reset_req
	);
end entity KBandIPsubPro_onchip_mem_LW;

architecture rtl of KBandIPsubPro_onchip_mem_LW is
	component KBandIPsubPro_onchip_mem_LW_altera_avalon_onchip_memory2_191_cauhtmy_cmp is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			address    : in  std_logic_vector(12 downto 0) := (others => 'X'); -- address
			clken      : in  std_logic                     := 'X';             -- clken
			chipselect : in  std_logic                     := 'X';             -- chipselect
			write      : in  std_logic                     := 'X';             -- write
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			reset      : in  std_logic                     := 'X';             -- reset
			reset_req  : in  std_logic                     := 'X';             -- reset_req
			freeze     : in  std_logic                     := 'X'              -- freeze
		);
	end component KBandIPsubPro_onchip_mem_LW_altera_avalon_onchip_memory2_191_cauhtmy_cmp;

	for onchip_mem_lw : KBandIPsubPro_onchip_mem_LW_altera_avalon_onchip_memory2_191_cauhtmy_cmp
		use entity altera_avalon_onchip_memory2_191.KBandIPsubPro_onchip_mem_LW_altera_avalon_onchip_memory2_191_cauhtmy;
begin

	onchip_mem_lw : component KBandIPsubPro_onchip_mem_LW_altera_avalon_onchip_memory2_191_cauhtmy_cmp
		port map (
			clk        => clk,        --   clk1.clk
			address    => address,    --     s1.address
			clken      => clken,      --       .clken
			chipselect => chipselect, --       .chipselect
			write      => write,      --       .write
			readdata   => readdata,   --       .readdata
			writedata  => writedata,  --       .writedata
			byteenable => byteenable, --       .byteenable
			reset      => reset,      -- reset1.reset
			reset_req  => reset_req,  --       .reset_req
			freeze     => '0'         -- (terminated)
		);

end architecture rtl; -- of KBandIPsubPro_onchip_mem_LW
