-- KBandIPsubPro_pio_0.vhd

-- Generated using ACDS version 19.1 240

library IEEE;
library altera_avalon_pio_191;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity KBandIPsubPro_pio_0 is
	port (
		clk        : in  std_logic                     := '0';             --                 clk.clk
		reset_n    : in  std_logic                     := '0';             --               reset.reset_n
		address    : in  std_logic_vector(1 downto 0)  := (others => '0'); --                  s1.address
		write_n    : in  std_logic                     := '0';             --                    .write_n
		writedata  : in  std_logic_vector(31 downto 0) := (others => '0'); --                    .writedata
		chipselect : in  std_logic                     := '0';             --                    .chipselect
		readdata   : out std_logic_vector(31 downto 0);                    --                    .readdata
		out_port   : out std_logic_vector(31 downto 0)                     -- external_connection.export
	);
end entity KBandIPsubPro_pio_0;

architecture rtl of KBandIPsubPro_pio_0 is
	component KBandIPsubPro_pio_0_altera_avalon_pio_191_ox4mioq_cmp is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			reset_n    : in  std_logic                     := 'X';             -- reset_n
			address    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			write_n    : in  std_logic                     := 'X';             -- write_n
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			chipselect : in  std_logic                     := 'X';             -- chipselect
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			out_port   : out std_logic_vector(31 downto 0)                     -- export
		);
	end component KBandIPsubPro_pio_0_altera_avalon_pio_191_ox4mioq_cmp;

	for pio_0 : KBandIPsubPro_pio_0_altera_avalon_pio_191_ox4mioq_cmp
		use entity altera_avalon_pio_191.KBandIPsubPro_pio_0_altera_avalon_pio_191_ox4mioq;
begin

	pio_0 : component KBandIPsubPro_pio_0_altera_avalon_pio_191_ox4mioq_cmp
		port map (
			clk        => clk,        --                 clk.clk
			reset_n    => reset_n,    --               reset.reset_n
			address    => address,    --                  s1.address
			write_n    => write_n,    --                    .write_n
			writedata  => writedata,  --                    .writedata
			chipselect => chipselect, --                    .chipselect
			readdata   => readdata,   --                    .readdata
			out_port   => out_port    -- external_connection.export
		);

end architecture rtl; -- of KBandIPsubPro_pio_0
